Modify some default attrs for resource.
eayunstack/zaqar pull request #10
Opened 2017-09-25 07:50 UTC by cdyangzhenyu

Modify some default attrs for resource.

redmine-11022

2017-09-25 08:20 UTC, huntxu requested changes

2017-09-25 08:20 UTC, huntxu commented on zaqar/storage/mongodb/queues.py
> +    def get_metadata(self, name, project=None, detailed=None):
这里应该`detailed`默认值是`False`?

2017-09-25 08:20 UTC, huntxu commented on zaqar/storage/mongodb/queues.py
> +                                          projection={'m': 1, 'p_q': 1,
`p_q`是表示什么，原来没用作搜索条件？还是为了下面那里的名字所以要加上，不是很清楚这里的projection是返回值还是搜索条件。

2017-09-25 08:20 UTC, huntxu commented on zaqar/storage/mongodb/queues.py
> +                                     'c': counter, 'c_t': now, 'u_t': now})
这里update的时间戳似乎应该保持None或者不设置合理点？因为并没有更新。不过还是看产品具体需求如何。

2017-09-25 08:20 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/queues.py
> -                    resp_dict[meta] = value
没有很明白这处改动的意义，原本有几个metadata是为None就不展现，现在删掉了？

2017-09-25 08:20 UTC, huntxu commented on zaqar/transport/base.py
> +    cfg.IntOpt('defalut_message_size', default=65535,
typo `defalut` :)
另外这个值和wiki上描述的不同，最终值65535还是65536？如果是大小的话，似乎64K整数好点

2017-09-25 08:20 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/topics.py
> -                        self._validate.get_limit_conf_value(meta)
没明白这处，好像和你想要做的事情不冲突啊，这里是获取另外一些配置默认值的样子呢，误操作删掉了？

2017-09-25 08:20 UTC, huntxu commented on zaqar/transport/base.py
> +    cfg.StrOpt('defalut_push_policy', default='EXPONENTIAL_DECAY_RETRY',
another `defalut`

2017-09-25 08:20 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/subscriptions.py
> +        return options
几个`_init*`的函数都一样的情况，因为传进来的是mutable的，并且你的调用也都是直接修改传进来的对象，所以可以的话把几个`return`都去掉比较好。

或者不传mutable参数进来，直接新生成外面用`dict.update`也可以，但是函数名可能就不适合叫`_init`。

2017-09-25 11:09 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/queues.py
> +    def get_metadata(self, name, project=None, detailed=None):
恩，这个可以改成False

2017-09-25 11:10 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/queues.py
> +                                          projection={'m': 1, 'p_q': 1,
projection这个是返回值里的key，如果是1就要返回，因为下面要用到，所以要加上，否则获取不到。

2017-09-25 11:11 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/queues.py
> +                                     'c': counter, 'c_t': now, 'u_t': now})
恩，这个根据要求刚创建是相同的。

2017-09-25 11:17 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/queues.py
> -                    resp_dict[meta] = value
恩，这个和我返回的metadata结构有冲突，原先的逻辑是库里可以没有元数据，但是get的时候根据初始值加上。现在是有初始化的操作，库里肯定有元数据，但是不是这个数据结构了，留着这个逻辑还会在加一遍元数据，返回的数据就会有重叠。这一块返回值是改了数据结构的，为了更符合产品的要求。

2017-09-25 11:27 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/topics.py
> -                        self._validate.get_limit_conf_value(meta)
这里和前面一样，因为已经初始化了，所以肯定是存在这些元数据的，而且数据结构也不一样，这样加了就重叠了，所以这里就没有存在的必要了。

2017-09-25 11:40 UTC, cdyangzhenyu commented on zaqar/transport/base.py
> +    cfg.StrOpt('defalut_push_policy', default='EXPONENTIAL_DECAY_RETRY',
没明白什么意思

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/queues.py
> -                    resp_dict[meta] = value
我知道了，我看代码的时候是一个一个commit看的，这个改动在queue timestamp的commit里面。看起来应该和timestamp这个commit没有关系，应该是第二个commit给queue加上默认属性的改动？

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/base.py
> +    cfg.IntOpt('defalut_message_size', default=65536,
还有typo，大概自动补全乱了？

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/base.py
> +    cfg.StrOpt('defalut_push_policy', default='EXPONENTIAL_DECAY_RETRY',
选项名里有typo

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/subscriptions.py
> +            'push_policy': 'defalut_push_policy'}
这里也拼错了，虽然两个地方一样也能用到...

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/queues.py
> +            '_max_messages_post_size': 'defalut_message_size',
这里配置项的名字里`default`也拼错了

2017-09-26 00:47 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/topics.py
> +            '_max_messages_post_size': 'defalut_message_size',
这里也有个拼写错误

2017-09-26 01:49 UTC, cdyangzhenyu commented on zaqar/transport/base.py
> +    cfg.IntOpt('defalut_message_size', default=65536,
哦 这个确实弄错了  手打的

2017-09-26 01:50 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/queues.py
> +            '_max_messages_post_size': 'defalut_message_size',
应该都是复制了一个错误的

2017-09-26 01:51 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/queues.py
> -                    resp_dict[meta] = value
恩 这个应该放到前面的提交

2017-09-26 02:47 UTC, huntxu approved these changes
thank you

2017-09-26 08:08 UTC, blkart commented on zaqar/transport/wsgi/v2_0/queues.py
> +                    get_limit_conf_value(default_key[meta])
感觉这部分的 ```meta```  改成 ```key``` 更易读

2017-09-26 08:08 UTC, blkart commented on zaqar/transport/wsgi/v2_0/topics.py
> +                    get_limit_conf_value(default_key[meta])
跟 queues 里面一样，感觉 ```meta``` 换成 ```key``` 好一点

2017-09-26 08:08 UTC, blkart commented on zaqar/transport/wsgi/v2_0/subscriptions.py
> +                    get_limit_conf_value(default_key[meta])
同 queues 和 topics，感觉 ```meta``` 换成 ```key``` 好一点

2017-09-26 08:31 UTC, merged