Fix consume exception when queue is not found.
eayunstack/zaqar pull request #18
Opened 2017-11-13 03:48 UTC by cdyangzhenyu

The current consumer messages, if the queue does not exist, it will raise a
500 error. This is not reasonable, so instead raise the 404 error.

redmine: http://192.168.15.2/issues/11172

2017-11-14 15:33 UTC, zh-f reviewed
看起来原先的处理是如果遇到不存在的情况，则重新创建？直接raise异常是不是不太妥当……

2017-11-15 01:32 UTC, cdyangzhenyu commented
@zh-f 这里就是要把直接重建的逻辑去掉，产品不允许重建，要抛出404的异常。否则如果上层出了问题就会有脏数据。

2017-11-15 01:36 UTC, zh-f approved these changes

2017-11-15 02:50 UTC, zhaochao reviewed
看起来是解决了 2 个问题：
1、500 错误，这个应该是错误调用了 queue_identification 方法；
2、去掉不存在的 queue 会自动创建的机制，这个问题则和 #17 （Redmine 11188） 相关， 11188 是发送，这个是消~息~费？

这样的话，如果不分成 2 个 commit ，也需要在 commit message 里说明一下。

2017-11-15 02:52 UTC, zhaochao requested changes
See the above comment.

2017-11-15 04:00 UTC, cdyangzhenyu commented
@zhaochao 这里算是解决了两个问题，因为直接去除自动创建的机制并且触发404的话，就不会有500的报错了。
另外#17是发送消息，这个是消费消息。

2017-11-15 04:12 UTC, zhaochao commented
@cdyangzhenyu 
对，上一条评论里说过了，如果没必要分成 2 个 commit 的话，应该在 commit message 里说明。

实际去掉原来的自动创建 queue 的机制，应该是单独作为一个 pull request ，发送和消费消息的改动都应该放进去。不过由于 pull request #17 已经改了一部份，在这个 pull request 再改一部份也是可以的。

另外还是有点担心，就去掉自动创建 queue 机制这个目标来说，不确定是不是还有没有改的地方。

2017-11-15 04:17 UTC, cdyangzhenyu commented
@zhaochao 这个由于是不同的issue所以就没有放到一起去改。目前针对队列的自动创建问题其他地方没有了。
commit message已经修改。

2017-11-15 04:27 UTC, zhaochao approved these changes

2017-11-15 06:08 UTC, huntxu commented
我搜`_queue_controller.create`发现在`api`里有两处是异常处理时调用，貌似也是类似发消息(`message_post`)和创建订阅(`subscription_create`)时自动创建了队列。看起来`api`里面的代码像是给websocket用的？没有仔细看。不确定是否要保证成一样的逻辑

2017-11-15 06:57 UTC, cdyangzhenyu commented
@huntxu 对的 api里的是给websocket使用的，我们目前没有用这个，所有的新增或者修改的功能都没有修改这个模块，因为涉及到很多的测试。以后如果要上webscket的话再修改吧。

2017-11-16 07:05 UTC, huntxu approved these changes

2017-11-16 07:05 UTC, merged