Add lock mechanism for zaqar.
eayunstack/zaqar pull request #21
Opened 2017-11-14 11:13 UTC by cdyangzhenyu

At present, some operations require a locking mechanism when concurrent
requests. This patch implements the basic logic of the lock. Added lock
handling for claim.

Redmine: http://192.168.15.2/issues/11195

2017-11-15 01:32 UTC, huntxu requested changes
release的实现有问题

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/base.py
> +        :param project: Project this monitor belongs to.
`monitor`?

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/driver.py
> +                    self.conf.profiler.trace_management_store)):
这两行看起来像有缩进问题，不过我没拉代码在本地跑

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/base.py
> +
`release()`看实现是有返回值，这里没说明

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/locks.py
> +                                    name, operation)
这个实现看起来怪怪的，每个锁的地方是否都会有独立的一个`LockController`的实例(看起来应该是共用的)？否则的话如果不同资源两次调用`get()`，那`self.key`会被刷新，影响release。`get()`和`is_locked()`本身倒不是很受这个变量的影响。但是这样看来`key`这个只是一个临时值的样子才对。

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
这里就会发生前面在`LockController`中提到的问题，`lock_ctrl.key`有机会被另外一个`get`重写，导致这里释放一个不该释放的，该释放的没有释放。

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/locks.py
> +    def is_locked(self, name, r_type, project, operation):
看后面的commit应该是没用好这个`is_locked`，原意是想在`release`的时候可以检查？

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/locks.py
> +        return True
后面四行是不是`return one is not None`？

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/locks.py
> +                                    name, operation)
这里可以定义个`_get_key`的helper function了

2017-11-15 01:32 UTC, huntxu commented on zaqar/storage/mongodb/locks.py
> +        return False
后面四行是不是return updated is not None？我不确定`self._col.update()`失败返回的是什么

2017-11-15 01:38 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
如果是进入到这里的话，别人是获取不到锁的。前面get的时候就会失败。

2017-11-15 01:41 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/driver.py
> +                    self.conf.profiler.trace_management_store)):
这个我跑了flake8没问题

2017-11-15 01:44 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
如果queue和project不同，那么两个get都会成功。这个时候release就有问题

2017-11-15 02:04 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
不同的话 是对应的不同的对象 所以不会有问题啊

2017-11-15 02:06 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/locks.py
> +                                    name, operation)
每一次并发请求都是对应的不同的对象，所以那个self.key在本对象里应该是没问题的。

2017-11-15 02:12 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/locks.py
> +    def is_locked(self, name, r_type, project, operation):
release里已经有检查是否有锁了。这个is_locked确实没有用到。这个是另外一个要用到锁的地方需要的，一会我会提交一个新的commit放到这个bp里，这个commit是解决另外一个issue的。

2017-11-15 02:18 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
就是说对不同的`queue`是不同的LockController实例？我在`LockController`那里已经有过这个疑问了。如果是多个LockController那就没有问题。只是直观上Controller这种应该只会被初始化一次才是

2017-11-15 02:58 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
是多个实例，可以看
def lock_controller(self):
      controller = controllers.LockController(self)

2017-11-15 03:10 UTC, cdyangzhenyu commented on zaqar/storage/base.py
> +        :param project: Project this monitor belongs to.
done

2017-11-15 03:10 UTC, cdyangzhenyu commented on zaqar/storage/base.py
> +
done

2017-11-15 03:11 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/locks.py
> +        return False
done

2017-11-15 03:11 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/locks.py
> +        return True
done

2017-11-15 03:13 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/locks.py
> +                                    name, operation)
done

2017-11-15 03:25 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
看起来还是有问题的样子啊，你引用的两行代码是`mongodb/driver.py`里的，lock_controller是一个lazy_property，也就是`self.driver`一样的话，lock_controller就是同一个。还是说连`self.driver`也是每次请求实例化一次？

2017-11-15 03:42 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
恩 这里确实可能存在问题，如果在同一个请求里有多个线程，并且要用这个锁的，而且都传同样的self.driver的话，可能就会有问题。但是不同的请求的话，这个self.driver是不同的实例。不过这样说的话，我觉得这里key还是需要改成局部的比较好。

2017-11-15 03:43 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +            lock_ctrl.release()
这个问题我确实测试过，因为在我这个场景里没有多线程，所以没有发现这个问题。两个请求之间打了断点，测了下确实是不会有问题的。

2017-11-15 06:30 UTC, huntxu approved these changes

2017-11-15 06:30 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +        lock = lock_ctrl.get(queue, 'queues', project, 'claim')
看起来加锁的操作是不是可以移动到170行之后，因为中间这部分只是获得消息列表。争抢发生的情况下，即使得到了消息列表也并没有关系。因为获取不到锁可以和没有消息供claim的情况相同处理(`return None, messages`)。这样子能做到一个get只对应后面那个release，没有两处

2017-11-15 06:55 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock = lock_ctrl.get(queue, 'queues', project, 'claim')
恩，这样说也可以，只是考虑到active这个函数可能会很耗时，因为消息可能会很多，既然有可能已经被锁，就没必要浪费计算资源了。

2017-11-15 07:05 UTC, huntxu commented on zaqar/transport/wsgi/v2_0/messages.py
> +                                                project_id, 'send_messages')
这个是无关的改动吧？

2017-11-15 07:06 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +        lock = lock_ctrl.get(queue, 'queues', project, 'claim')
如果考虑active的时间情况的话，claim的锁的ttl默认值只给了1s，是否足够？因为这里有手动的释放，ttl给一个比较大的值应该没有问题才是

2017-11-15 07:35 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock = lock_ctrl.get(queue, 'queues', project, 'claim')
因为mongo自动清除是有可能延迟60s的，也就是清除时间是在1-61s的范围内。这里也只能尽量保证加锁，毕竟这个问题是非常偶然的问题。如果出现时间过期被删除，然后锁失效，那也确实没办法了。这里不调太大是考虑到claim这个操作是相当频繁的，如果锁释放出了问题，或者异常导致锁没有释放，或者释放之前服务重启了，就会出现比较长的时间无法claim，这就影响了正常的业务逻辑。跟重复claim比起来，正常claim受影响就更严重了。

2017-11-15 07:38 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/messages.py
> +                                                project_id, 'send_messages')
如果队列正在被清空导致队列被锁的话，此时发送消息就会失败，从而返回空的消息，而这些消息不应该被统计到才对。

2017-11-15 07:41 UTC, zhaochao commented on zaqar/storage/mongodb/locks.py
> +        return True if updated else False
看了下 pymongodb 的 collection.update 的说明，更新不成功时应该是也会返回一个 dict 对象的？

2017-11-15 07:41 UTC, zhaochao commented on zaqar/transport/wsgi/v2_0/messages.py
> +                                                project_id, 'send_messages')
+1

2017-11-15 08:17 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
我注意到下面222行到227行的注释，看起来已经处理了同时获取一条消息的情况的样子，只是该消息的属性总是会被先更新，但最终返回的消息是按claim ID的tag返回的，也就是只有一个claim能获取到该条消息，不会被多个地方claim到。看起来只是cousume次数的计数出了问题。加上锁的机制似乎把问题更复杂化了。

仔细分析这段代码，看起来183行的`update`应该是没有问题的，如果170行到181行的注释成立的话，只判断和更新`c.e`应该是足够应对争抢。196行的`update`看起来也没有问题，因为根据`c.id`去搜索了属于这个claim的内容了。

看起来有问题的应该是212行的这个`update`，因为没有做任何过滤，将前面得到的active messages，不管情况都做了信息的更新，其中包括了consume_count这个展现出来让人误以为被多次消费的值。看样子只需要在212行这个update仿照前一个加上`c.id`的过滤就可以了？

2017-11-15 09:15 UTC, zhaochao commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
+1

目前加上一个单独的锁有点复杂化了，因为看上去 MongoDB 的 collection.update 是能保证原子性，新的锁机制也是利用了这一点，因此如果只是为了解决同一条消息在 claim 锁定期间只被消费一次，应该可以同样只是通过更新 claim 相关信息时 update 方法就可以。

@huntxu 的意见应该没错，前面获取临时变量 updated  时执行的 collection.update 的确已经对 c.e 进行过滤，这样已经能保证，设置了 c.id 的消息不会被消费多次。

2017-11-15 09:18 UTC, zhaochao requested changes
见 inline comments 。

2017-11-15 09:28 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
恩 这里确实是这样的， 这个提交可能要分开了。把锁放到purge那里吧 重新在开一个pr。

2017-11-15 09:38 UTC, cdyangzhenyu commented on zaqar/transport/wsgi/v2_0/messages.py
> +                                                project_id, 'send_messages')
这个确实不是很合理 但是这是产品定的指标 清空的过程中不能有消息发送进去。

2017-11-15 09:42 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
我觉得202这个处理可能要放到228后面就没问题了。

2017-11-15 09:54 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
@zhaochao  这里是要考虑同一时刻去消费，不是被锁定期间再次消费。目前原生这个机制确实能保证同一时刻并发消费时只返回一个，但是具体是哪一个就可能出现oid被覆盖的情况，有可能先消费但没有消费到消息的情况。后面的统计是我加的，这个确实加的有问题，这个还需要在考虑考虑。但是这个循环好像避免不了，看看放到228后面，但是也要后面再get一次才行。 @huntxu

2017-11-15 10:05 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
看起来oid是不会被覆盖的才是。183行的`update`已经比较并更新了`c.e`，原子性由MongoDB本身保证。因为`c.e`更新了，同时争抢的其他claim同样到这行代码的话那个`'c.e': {'$lte': now}`的比较不会成立，因此当一个消息的oid确定时，短时间内不会被其他的oid覆盖。

如果上面这个是成立的话，@cdyangzhenyu 似乎像你前面说的把对message的更新放到后面针对具体被这个claim所消费的消息，而不是所有active messages进行更新就可以了。

2017-11-15 10:16 UTC, zhaochao commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
@cdyangzhenyu 
同一时刻消费结果是一样的吧，应该只有一个 claim 操作会更一批消息的，那么对于这一批消息来说，另外的 claim 操作同样也是锁定期间发生的，当前前提是 MongoDB 的 collection.update 是保证原子性的。

至于后面的统计部份，加上 c.id 过滤之后正常应该也是没有问题的，除非这个循环在锁定期间还没有完成，而且新的 claim 操作已经再次更新了某些消息的 c.id 。

不过看起来，像 cc 和 nc_t 应该都可以在上面 L183 的 update 里一次性完成（不太了解 fc_t 的作用，所以不能确定是不是也可以）。

2017-11-15 10:27 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +        lock_ctrl.release(queue, 'queues', project, 'claim')
恩 那在原来的基础上把c.id的过滤加上应该就可以了。 cc和nc_t确实在上面可以更新，但是fc_t这个是要有个判断的，mongo好像不支持批量判断更新。

2017-11-16 02:05 UTC, huntxu reviewed
我注意到mongodb有`$inc`的指令，`$set`的时候有`exists`的判断。所以看起来这里有机会能把202行这个`update`合并到前面的update去，不过由于`cc`原来可能不存在所以可能要分两次。但比起逐个消息循环获取更新应该会好点。

另外有两个关系不大的意见，应该是之前没注意。

2017-11-16 02:05 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
看起来这两行其实是把197行的`None`改成`now`就是了

2017-11-16 02:05 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
>                                 'c_id': objectid.ObjectId(),
这个`c_id`没怎么看出来用途，给了一个随机生成的`ObjectId`不确定是要干什么，因为没缓存下来这个值，所以好像只是类似往数据里随便填了个值的样子？

2017-11-16 03:09 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
>                                 'c_id': objectid.ObjectId(),
这个是必须的，每一个消费的消息都有一个独立的id，这和原生的zaqar设计不一样，拿着这个独立的id可以去删除消费过的消息。

2017-11-16 03:12 UTC, cdyangzhenyu commented
@huntxu 这个我试过了 直接把inc加到上面的update里 直接报错了 可能目前用的2.6版本不支持批量inc？而且下面那个c_id是每个消费消息都不同且唯一的，每一次消费都会生成一个。要更新这个就只能循环了。

2017-11-16 03:31 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
197行的`first_consumed_at`是可能存在的，也可能为`None`，直接改成`now`应该是不行的，不过也可以写成简写，在后面加if

2017-11-16 03:35 UTC, zhaochao commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
@cdyangzhenyu 
之前的评论提过，cc 和 nc_t 可以直接放到 L173 的 collection.update 里去，fc_t 这个 field 看起来影响较小，单独放在 for 循环里应该没事。

2017-11-16 03:45 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
@zhaochao 这个我试过，直接加`$inc`要报错，不知道是不是`multi=true`的时候不支持还是版本不支持，考虑到这个循环怎么样都去不掉，那就没必要改太多原生代码了。

2017-11-16 03:54 UTC, zhaochao commented
@cdyangzhenyu 
我刚去成都环境 zaqar container 里试了下，确认 collection.update 用 $inc （multi=True）没什么问题。

@huntxu 提到的 $exists ，我也看了下，对于 fc_t 的更新也是一个方案，不过这样的上面 L173 那里要变成 2 次 collection.update ，一次针对 fc_t 不存在的（设置 fc_t 为当前时间），一次针对 fc_t 已经存在（不更新 fc_t）。

2017-11-16 03:54 UTC, huntxu commented
> @huntxu 这个我试过了 直接把inc加到上面的update里 直接报错了 可能目前用的2.6版本不支持批量inc？而且下面那个c_id是每个消费消息都不同且唯一的，每一次消费都会生成一个。要更新这个就只能循环了。

报错的原因是否因为`cm.cc`不存在，我前面也说过了可能需要分成两次，第一次确保`cm.cc`若不存在设置为0，第二次执行`$inc`。看mongodb 2.6文档，也没明确提到`$inc`这个操作不支持批量

2017-11-16 03:56 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
>                                 'c_id': objectid.ObjectId(),
这个不明白，消息本身就有独立的id存在。被消费过的消息，`cm`是存在的。没有什么必要拿另外一个字段来表示是否消费过吧？而且这个随机值没有缓存下来，也不像给外部用的

2017-11-16 04:00 UTC, huntxu commented
> @huntxu 提到的 $exists ，我也看了下，对于 fc_t 的更新也是一个方案，不过这样的上面 L173 那里要变成 2 次 collection.update ，一次针对 fc_t 不存在的（设置 fc_t 为当前时间），一次针对 fc_t 已经存在（不更新 fc_t）。

fc_t不存在其实应该就是cm不存在。所以问题应该能简化为，未被消费的消息判断并设置默认cm(cc=1, fc_t=首次时间, nc_t)，之前被消费过的消息更新cm($inc(cc), 更新nc_t)。

2017-11-16 04:04 UTC, zhaochao commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
@cdyangzhenyu 
$inc 在另外一个评论回复了。

cc 、nc_t 、fc_t 这些放到 L173 那里比较安全，放在 for 循环里终究出错的概率大一些。剩下那个 c_id 其实也考虑放到一起比较好。

2017-11-16 04:13 UTC, zhaochao commented
> fc_t不存在其实应该就是cm不存在。所以问题应该能简化为，未被消费的消息判断并设置默认cm(cc=1, fc_t=首次时间, nc_t)，之前被消费过的消息更新cm($inc(cc), 更新nc_t)。

对，的确是这样。判断 cm 存不存就可以。

2017-11-16 05:40 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
>                                 'c_id': objectid.ObjectId(),
cm是要存到库里的。每个消息每次消费都需要给一个消费的handle，这个是产品要求。这个不同于消息id。这个id只有在消费时才会生成，每次消费同一个消息时该id都要求不同。

2017-11-16 06:25 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
>                                 'c_id': objectid.ObjectId(),
我去看了需求文档明白了。

2017-11-16 06:27 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
>                  cm['fc_t'] = now
恩，那可能是我当时试的时候哪里写错了。我再试试。但是c_id好像没法放到一起，mongo没有类似的操作符。

2017-11-16 06:34 UTC, cdyangzhenyu commented
@huntxu @zhaochao 已经更新，将`cc`,`nc_t`,`fc_t`放到批量更新里。但是`c_id`貌似没有办法批量更新。

2017-11-16 06:42 UTC, huntxu reviewed
`$inc`的使用还有疑问，其他的没问题。

2017-11-16 06:42 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +                                     '$inc': {'cm.cc': 1}},
这个能照顾到原本没有`cm.cc`的情况吗？会默认用0然后加1？

2017-11-16 06:42 UTC, huntxu commented on zaqar/storage/mongodb/claims.py
> +                               'c_id': objectid.ObjectId()}},
这个循环看起来因为设计原因没法避免。不知道这样循环执行和用mongo的multiple update性能上的区别有没有很明显，如果没有倒也还好。

我看了需求，其实这里并不需要随机单独给一个c_id来作为消费句柄，所谓消费句柄其实只要返回时拿消息id加上c.id这个claim的oid两个合并就能标示一个被消费过的且不公开的id。一旦被再次消费由于oid变了所以消费句柄这个东西就变了，也能实现目的。不过这个一时半会估计改不过来了，暂时这样吧，等实在发现这里有性能问题再说，

2017-11-16 06:48 UTC, zhaochao approved these changes

2017-11-16 06:48 UTC, zhaochao commented on zaqar/storage/mongodb/claims.py
> +                                     '$inc': {'cm.cc': 1}},
这个查了下，看起来没问题，field 不存，会直接创建 field ，并设置为指定的值（这里就是 1）。

2017-11-16 06:48 UTC, zh-f commented on zaqar/storage/mongodb/claims.py
> +                                     '$inc': {'cm.cc': 1}},
The $inc operator accepts positive and negative values.

If the field does not exist, $inc creates the field and sets the field to the specified value.

Use of the $inc operator on a field with a null value will generate an error.

$inc is an atomic operation within a single document.

via https://docs.mongodb.com/manual/reference/operator/update/inc/index.html

2017-11-16 06:49 UTC, zh-f approved these changes
👍

2017-11-16 06:54 UTC, huntxu approved these changes

2017-11-16 06:55 UTC, merged

2017-11-16 06:56 UTC, huntxu commented
@zhaochao @zh-f thx。我有看文档，只是翻得太快了...

2017-11-16 07:09 UTC, cdyangzhenyu commented on zaqar/storage/mongodb/claims.py
> +                               'c_id': objectid.ObjectId()}},
恩 确实如此

2017-11-21 05:32 UTC, cdyangzhenyu commented
需要重新修改，所以先revert